### ISSUE TITLE
Assertion instead of Error message while updating gardenlinux submodule

### ISSUE THREAD

**Issue by toanju** [gardenlinux/gardenlinux-sci#19]
**What happened**:

Updated gardenlinux submodul.

**What you expected to happen**:

Nicer error messages instead of an assertion:

```
$ ./.build.sh
Traceback (most recent call last):
  File "/builder/./parse_features", line 223, in <module>
    main()
  File "/builder/./parse_features", line 75, in main
    feature_graph = read_feature_files(args.feature_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builder/./parse_features", line 187, in read_feature_files
    assert os.path.isfile(f"{feature_dir}/{ref}/info.yaml"), f"feature {node} references feature {ref}, but {feature_dir}/{ref}/info.yaml does not exist"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: feature cloud references feature _legacy, but features/_legacy/info.yaml does not exist
Traceback (most recent call last):
  File "/builder/./parse_features", line 223, in <module>
    main()
  File "/builder/./parse_features", line 75, in main
    feature_graph = read_feature_files(args.feature_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builder/./parse_features", line 187, in read_feature_files
    assert os.path.isfile(f"{feature_dir}/{ref}/info.yaml"), f"feature {node} references feature {ref}, but {feature_dir}/{ref}/info.yaml does not exist"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: feature cloud references feature _legacy, but features/_legacy/info.yaml does not exist
make: *** No rule to make target 'openstackbaremetal-metal3-orabos-amd64'.  Stop.
```

Would be great if this directly points out to `feature _legacy is missing`

**Comment by sramapu** [comment]
Closing due to no activity for more than 500d
